#pragma once

#define ANALOG_JOYSTICK_X_AXIS_PIN F5
#define ANALOG_JOYSTICK_Y_AXIS_PIN F6

// #define ANALOG_JOYSTICK_AXIS_MAX 256
// #define ANALOG_JOYSTICK_SPEED_REGULATOR 40


#define ANALOG_JOYSTICK_READ_INTERVAL 1
// #define ANALOG_JOYSTICK_SPEED_MAX 5